""" Adding `always_show_ticket_number` to display screen settings.

Revision ID: 1728b52497ba
Revises: 8f8e67fcbd9c
Create Date: 2020-02-12 05:47:13.140826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1728b52497ba'
down_revision = '8f8e67fcbd9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column('displays', sa.Column('always_show_ticket_number', sa.Boolean(), nullable=True))
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('displays') as batch:
        batch.drop_column('always_show_ticket_number')
    # ### end Alembic commands ###
