""" Drop `Waiting` table, no longer needed 🕺

Revision ID: 1ab329f328d9
Revises: afc9e6d4decc
Create Date: 2020-02-13 17:15:58.700250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab329f328d9'
down_revision = 'afc9e6d4decc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_table('waitings')
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitings',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('number', sa.INTEGER(), nullable=True),
                    sa.Column('name', sa.VARCHAR(length=300), nullable=True),
                    sa.Column('n', sa.BOOLEAN(), nullable=True),
                    sa.Column('office_id', sa.INTEGER(), nullable=True),
                    sa.Column('task_id', sa.INTEGER(), nullable=True),
                    sa.CheckConstraint('n IN (0, 1)'),
                    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
                    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
                    sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###
