"""Initial migration.

Revision ID: 60d8ec92c248
Revises: 27a0b5682c34
Create Date: 2022-07-21 02:57:52.534736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d8ec92c248'
down_revision = '27a0b5682c34'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table('aliases',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('office', sa.String(length=100), nullable=True),
        sa.Column('task', sa.String(length=100), nullable=True),
        sa.Column('ticket', sa.String(length=100), nullable=True),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('number', sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('background_tasks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('enabled', sa.Boolean(), nullable=True),
        sa.Column('every', sa.String(length=10), nullable=True),
        sa.Column('time', sa.Time(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )
        op.create_table('media',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vid', sa.Boolean(), nullable=True),
        sa.Column('audio', sa.Boolean(), nullable=True),
        sa.Column('img', sa.Boolean(), nullable=True),
        sa.Column('used', sa.Boolean(), nullable=True),
        sa.Column('name', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('offices',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=300), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('prefix', sa.String(length=2), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )
        op.create_index(op.f('ix_offices_timestamp'), 'offices', ['timestamp'], unique=False)
        op.create_table('printers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vendor', sa.Integer(), nullable=True),
        sa.Column('product', sa.Integer(), nullable=True),
        sa.Column('in_ep', sa.Integer(), nullable=True),
        sa.Column('out_ep', sa.Integer(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('langu', sa.String(length=100), nullable=True),
        sa.Column('value', sa.Integer(), nullable=True),
        sa.Column('scale', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('header', sa.String(length=50), nullable=True),
        sa.Column('sub', sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('product'),
        sa.UniqueConstraint('vendor')
        )
        op.create_table('roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )
        op.create_table('settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('notifications', sa.Boolean(), nullable=True),
        sa.Column('strict_pulling', sa.Boolean(), nullable=True),
        sa.Column('visual_effects', sa.Boolean(), nullable=True),
        sa.Column('lp_printing', sa.Boolean(), nullable=True),
        sa.Column('single_row', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('slides_c',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('rotation', sa.String(length=100), nullable=True),
        sa.Column('navigation', sa.Integer(), nullable=True),
        sa.Column('effect', sa.String(length=100), nullable=True),
        sa.Column('status', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('tasks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=300), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('hidden', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_tasks_timestamp'), 'tasks', ['timestamp'], unique=False)
        op.create_table('auth_tokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('description', sa.String(length=300), nullable=True),
        sa.Column('token', sa.String(length=32), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('token')
        )
        op.create_table('displays',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=300), nullable=True),
        sa.Column('hsize', sa.String(length=100), nullable=True),
        sa.Column('hcolor', sa.String(length=100), nullable=True),
        sa.Column('h2size', sa.String(length=100), nullable=True),
        sa.Column('h2color', sa.String(length=100), nullable=True),
        sa.Column('h2font', sa.String(length=100), nullable=True),
        sa.Column('hbg', sa.String(length=100), nullable=True),
        sa.Column('tsize', sa.String(length=100), nullable=True),
        sa.Column('tcolor', sa.String(length=100), nullable=True),
        sa.Column('ssize', sa.String(length=100), nullable=True),
        sa.Column('scolor', sa.String(length=100), nullable=True),
        sa.Column('audio', sa.String(length=10), nullable=True),
        sa.Column('hfont', sa.String(length=100), nullable=True),
        sa.Column('tfont', sa.String(length=100), nullable=True),
        sa.Column('sfont', sa.String(length=100), nullable=True),
        sa.Column('mduration', sa.String(length=100), nullable=True),
        sa.Column('rrate', sa.String(length=100), nullable=True),
        sa.Column('announce', sa.String(length=100), nullable=True),
        sa.Column('anr', sa.Integer(), nullable=True),
        sa.Column('anrt', sa.String(length=100), nullable=True),
        sa.Column('effect', sa.String(length=100), nullable=True),
        sa.Column('repeats', sa.String(length=100), nullable=True),
        sa.Column('bgcolor', sa.String(length=100), nullable=True),
        sa.Column('tmp', sa.Integer(), nullable=True),
        sa.Column('prefix', sa.Boolean(), nullable=True),
        sa.Column('always_show_ticket_number', sa.Boolean(), nullable=True),
        sa.Column('wait_for_announcement', sa.Boolean(), nullable=True),
        sa.Column('hide_ticket_index', sa.Boolean(), nullable=True),
        sa.Column('r_announcement', sa.Boolean(), nullable=True),
        sa.Column('akey', sa.Integer(), nullable=True),
        sa.Column('ikey', sa.Integer(), nullable=True),
        sa.Column('vkey', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['akey'], ['media.id'], ondelete='cascade'),
        sa.ForeignKeyConstraint(['ikey'], ['media.id'], ondelete='cascade'),
        sa.ForeignKeyConstraint(['vkey'], ['media.id'], ondelete='cascade'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('mtasks',
        sa.Column('office_id', sa.Integer(), nullable=False),
        sa.Column('task_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
        sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
        sa.PrimaryKeyConstraint('office_id', 'task_id')
        )
        op.create_table('operators',
        sa.Column('crap', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=True),
        sa.Column('office_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
        sa.PrimaryKeyConstraint('crap')
        )
        op.create_table('serials',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('number', sa.Integer(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('name', sa.String(length=300), nullable=True),
        sa.Column('n', sa.Boolean(), nullable=True),
        sa.Column('p', sa.Boolean(), nullable=True),
        sa.Column('pdt', sa.DateTime(), nullable=True),
        sa.Column('pulledBy', sa.Integer(), nullable=True),
        sa.Column('on_hold', sa.Boolean(), nullable=True),
        sa.Column('status', sa.String(length=10), nullable=True),
        sa.Column('office_id', sa.Integer(), nullable=True),
        sa.Column('task_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
        sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_serials_timestamp'), 'serials', ['timestamp'], unique=False)
        op.create_table('slides',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=300), nullable=True),
        sa.Column('hsize', sa.String(length=100), nullable=True),
        sa.Column('hcolor', sa.String(length=100), nullable=True),
        sa.Column('hfont', sa.String(length=100), nullable=True),
        sa.Column('hbg', sa.String(length=100), nullable=True),
        sa.Column('subti', sa.String(length=300), nullable=True),
        sa.Column('tsize', sa.String(length=100), nullable=True),
        sa.Column('tcolor', sa.String(length=100), nullable=True),
        sa.Column('tfont', sa.String(length=100), nullable=True),
        sa.Column('tbg', sa.String(length=100), nullable=True),
        sa.Column('bname', sa.String(length=300), nullable=True),
        sa.Column('ikey', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['ikey'], ['media.id'], ondelete='cascade'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('touchs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=300), nullable=True),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('hsize', sa.String(length=100), nullable=True),
        sa.Column('hcolor', sa.String(length=100), nullable=True),
        sa.Column('hbg', sa.String(length=100), nullable=True),
        sa.Column('tsize', sa.String(length=100), nullable=True),
        sa.Column('tcolor', sa.String(length=100), nullable=True),
        sa.Column('msize', sa.String(length=100), nullable=True),
        sa.Column('mcolor', sa.String(length=100), nullable=True),
        sa.Column('mbg', sa.String(length=100), nullable=True),
        sa.Column('audio', sa.String(length=100), nullable=True),
        sa.Column('hfont', sa.String(length=100), nullable=True),
        sa.Column('mfont', sa.String(length=100), nullable=True),
        sa.Column('tfont', sa.String(length=100), nullable=True),
        sa.Column('mduration', sa.String(length=100), nullable=True),
        sa.Column('bgcolor', sa.String(length=100), nullable=True),
        sa.Column('p', sa.Boolean(), nullable=True),
        sa.Column('n', sa.Boolean(), nullable=True),
        sa.Column('tmp', sa.Integer(), nullable=True),
        sa.Column('akey', sa.Integer(), nullable=True),
        sa.Column('ikey', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['akey'], ['media.id'], ondelete='cascade'),
        sa.ForeignKeyConstraint(['ikey'], ['media.id'], ondelete='cascade'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=True),
        sa.Column('password_hash', sa.String(length=128), nullable=True),
        sa.Column('last_seen', sa.DateTime(), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )
        op.create_index(op.f('ix_users_last_seen'), 'users', ['last_seen'], unique=False)
        op.create_table('vids',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vname', sa.String(length=300), nullable=True),
        sa.Column('enable', sa.Integer(), nullable=True),
        sa.Column('ar', sa.Integer(), nullable=True),
        sa.Column('controls', sa.Integer(), nullable=True),
        sa.Column('mute', sa.Integer(), nullable=True),
        sa.Column('vkey', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['vkey'], ['media.id'], ondelete='cascade'),
        sa.PrimaryKeyConstraint('id')
        )
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_table('vids')
        op.drop_index(op.f('ix_users_last_seen'), table_name='users')
        op.drop_table('users')
        op.drop_table('touchs')
        op.drop_table('slides')
        op.drop_index(op.f('ix_serials_timestamp'), table_name='serials')
        op.drop_table('serials')
        op.drop_table('operators')
        op.drop_table('mtasks')
        op.drop_table('displays')
        op.drop_table('auth_tokens')
        op.drop_index(op.f('ix_tasks_timestamp'), table_name='tasks')
        op.drop_table('tasks')
        op.drop_table('slides_c')
        op.drop_table('settings')
        op.drop_table('roles')
        op.drop_table('printers')
        op.drop_index(op.f('ix_offices_timestamp'), table_name='offices')
        op.drop_table('offices')
        op.drop_table('media')
        op.drop_table('background_tasks')
        op.drop_table('aliases')
    except Exception:
        pass
    # ### end Alembic commands ###
