""" Adding `visual_effects` flag setting.

Revision ID: 8aee5e17a98d
Revises: f4efa0d99d19
Create Date: 2020-02-10 01:58:58.632105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aee5e17a98d'
down_revision = 'f4efa0d99d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column('settings', sa.Column('visual_effects', sa.Boolean(), nullable=True))
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings') as batch:
        batch.drop_column('visual_effects')
    # ### end Alembic commands ###
