""" Adding `on_hold` flag to tickets.

Revision ID: 8f8e67fcbd9c
Revises: 8aee5e17a98d
Create Date: 2020-02-10 20:07:59.376033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8e67fcbd9c'
down_revision = '8aee5e17a98d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column('serials', sa.Column('on_hold', sa.Boolean(), nullable=True))
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serials') as batch:
        batch.drop_column('on_hold')
    # ### end Alembic commands ###
