""" Drop `Waiting_c` table, no longer needed 🕺

Revision ID: afc9e6d4decc
Revises: 1728b52497ba
Create Date: 2020-02-13 17:04:26.460183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc9e6d4decc'
down_revision = '1728b52497ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_table('waitings_c')
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitings_c',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('ticket', sa.VARCHAR(), nullable=True),
                    sa.Column('oname', sa.VARCHAR(), nullable=True),
                    sa.Column('tname', sa.VARCHAR(), nullable=True),
                    sa.Column('n', sa.BOOLEAN(), nullable=True),
                    sa.Column('name', sa.VARCHAR(length=300), nullable=True),
                    sa.CheckConstraint('n IN (0, 1)'),
                    sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###
